package com.example.myagent.ui.theme

import androidx.compose.ui.graphics.Color

val CreamBackground = Color(0xFFF7F0E1)
val CreamOnBackground = Color(0xFF221B12)
val CreamSurface = Color(0xFFFDF9F0)
val CreamOnSurface = Color(0xFF221B12)
val CreamSurfaceVariant = Color(0xFFE9DFC8)
val CreamOnSurfaceVariant = Color(0xFF6B6152)
val PosterRed = Color(0xFFD62800)
val OnPosterRed = Color(0xFFFFFFFF)
val PosterRedContainer = Color(0xFFF3D3C2)
val OnPosterRedContainer = Color(0xFF221B12)
val BurntOrange = Color(0xFFA03E00)
val BurntOrangeContainer = Color(0xFFE8C29E)
val OnBurntOrangeContainer = Color(0xFF221B12)
val PosterBlue = Color(0xFF203A6B)
val PosterBlueContainer = Color(0xFFB9C7E0)
val OnPosterBlueContainer = Color(0xFF221B12)
val CreamError = Color(0xFF8C1D18)
val CreamErrorContainer = Color(0xFFF3C6C1)
val OnCreamErrorContainer = Color(0xFF221B12)
val PosterOutline = Color(0xFF9A8F7C)

val GraphitBackground = Color(0xFF1E100F)
val GraphitOnBackground = Color(0xFFF2E7DA)
val GraphitSurface = Color(0xFF2A1B17)
val GraphitOnSurface = Color(0xFFF2E7DA)
val GraphitSurfaceVariant = Color(0xFF3E2A24)
val GraphitOnSurfaceVariant = Color(0xFFC7B7A5)
val GraphitPrimary = Color(0xFFFF6A44)
val GraphitOnPrimary = Color(0xFF24140B)
val GraphitPrimaryContainer = Color(0xFF9E3C22)
val GraphitOnPrimaryContainer = Color(0xFFF2E7DA)
val GraphitSecondary = Color(0xFFFFB257)
val GraphitSecondaryContainer = Color(0xFF7A3F08)
val GraphitOnSecondaryContainer = Color(0xFFF2E7DA)
val GraphitTertiary = Color(0xFF9DB4E8)
val GraphitTertiaryContainer = Color(0xFF2D4A80)
val GraphitOnTertiaryContainer = Color(0xFFF2E7DA)
val GraphitError = Color(0xFFFFB4AB)
val GraphitErrorContainer = Color(0xFF5B1F1C)
val GraphitOnErrorContainer = Color(0xFFF2E7DA)
val GraphitOutline = Color(0xFF6E5F52)