package com.example.myagent.ui.theme

import androidx.compose.ui.graphics.Color

val CreamBackground = Color(0xFFFAFAF8)
val CreamOnBackground = Color(0xFF1A1A1A)
val CreamSurface = Color(0xFFFFFFFF)
val CreamOnSurface = Color(0xFF1A1A1A)
val CreamSurfaceVariant = Color(0xFFF0EFEC)
val CreamOnSurfaceVariant = Color(0xFF6B6B6B)
val PosterRed = Color(0xFFC4341F)
val OnPosterRed = Color(0xFFFFFFFF)
val PosterRedContainer = Color(0xFFF0D9D2)
val OnPosterRedContainer = Color(0xFF1A1A1A)
val CreamSecondary = Color(0xFF1B2A4A)
val OnCreamSecondary = Color(0xFFFFFFFF)
val CreamSecondaryContainer = Color(0xFFC9D3E8)
val OnCreamSecondaryContainer = Color(0xFF1A1A1A)
val PosterBlue = Color(0xFF203A6B)
val PosterBlueContainer = Color(0xFFC9D3E8)
val OnPosterBlueContainer = Color(0xFF1A1A1A)
val CreamError = Color(0xFFB3261E)
val CreamErrorContainer = Color(0xFFF3D8D6)
val OnCreamErrorContainer = Color(0xFF1A1A1A)
val PosterOutline = Color(0xFFCCCCCC)

val GraphitBackground = Color(0xFF1E100F)
val GraphitOnBackground = Color(0xFFF2E7DA)
val GraphitSurface = Color(0xFF2A1B17)
val GraphitOnSurface = Color(0xFFF2E7DA)
val GraphitSurfaceVariant = Color(0xFF3E2A24)
val GraphitOnSurfaceVariant = Color(0xFFC7B7A5)
val GraphitPrimary = Color(0xFFFF6A44)
val GraphitOnPrimary = Color(0xFF24140B)
val GraphitPrimaryContainer = Color(0xFF9E3C22)
val GraphitOnPrimaryContainer = Color(0xFFF2E7DA)
val GraphitSecondary = Color(0xFFFFB257)
val GraphitSecondaryContainer = Color(0xFF7A3F08)
val GraphitOnSecondaryContainer = Color(0xFFF2E7DA)
val GraphitTertiary = Color(0xFF9DB4E8)
val GraphitTertiaryContainer = Color(0xFF2D4A80)
val GraphitOnTertiaryContainer = Color(0xFFF2E7DA)
val GraphitError = Color(0xFFFFB4AB)
val GraphitErrorContainer = Color(0xFF5B1F1C)
val GraphitOnErrorContainer = Color(0xFFF2E7DA)
val GraphitOutline = Color(0xFF6E5F52)